version: 2
jobs:
  build:
    docker:
      - image: edy555/arm-embedded:4.9
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: "Build Firmware"
          command: make VERSION=\"${CIRCLE_TAG}\"
      - run:
          name: "Remove obj/lst files"
          command: rm -r build/obj build/lst
      - run:
          name: "Archive artifacts"
          command: mkdir archives && zip archives/nanovna-firmware-${CIRCLE_TAG}.zip build/*.bin build/*.hex build/*.elf
      - store_artifacts:
          path: build
          destination: build
      - store_artifacts:
          path: archives
          destination: .
      - persist_to_workspace:
          root: archives
          paths:
            - .
  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} nanovna-firmware-${CIRCLE_TAG}.zip
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              # 1.0.0
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              # 1.0.0
              only: /^\d+\.\d+\.\d+$/